/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-03 10:10:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.heabom.member.model.vo.Member;

public final class boardEnrollForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/board/../common/header.jsp", Long.valueOf(1693575024863L));
    _jspx_dependants.put("/views/board/../common/sidebar.jsp", Long.valueOf(1693492663994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("        integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("        integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        div {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrap {\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 캐러셀 관련 */\r\n");
      out.write("        .carousel {\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-inner {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-item {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-inner>div>img {\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 캐러셀 관련 끝*/\r\n");
      out.write("\r\n");
      out.write("        /* 글쓰기 글자 폼 */\r\n");
      out.write("        #write-text {\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            line-height: 19px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-text>div {\r\n");
      out.write("            padding-top: 10px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            border-bottom: 3px solid gray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 글쓰기 글자 폼 끝 */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* 글쓰기 폼 */\r\n");
      out.write("\r\n");
      out.write("        .write-post-area {\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-post-header {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-post-header>div {\r\n");
      out.write("            float: left;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-post-header>div>* {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-post-title-area {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            padding-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #select-category-area {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-poster-footer {\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #write-poster-footer>div {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #writer-poster-submit {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #admin-private {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #notice-check {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            top: 2px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #notice-check-text {\r\n");
      out.write("            position: relative;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .note-resizebar {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .note-statusbar {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 해시태그 관련 */\r\n");
      out.write("        span {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            /*border: 1px solid black;*/\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag {\r\n");
      out.write("            height: auto;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag>span {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag>span>* {\r\n");
      out.write("            float: left;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag>span>span {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-left: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag>span>div input {\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            width: 70px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #input-tag>span>div input:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tag-input-area button {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .parent-span{\r\n");
      out.write("        	padding-right: 10px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 해시태그 관련 끝 */\r\n");
      out.write("\r\n");
      out.write("        /* 글쓰기 폼 끝 */\r\n");
      out.write("        /* 파일 테이블 */\r\n");
      out.write("        #fileTable{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            /* border: 1px solid red */ \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath = request.getContextPath();
	Member loginMember =  (Member)session.getAttribute("loginMember");
	
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"wWidth=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=IBM+Plex+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script><!--alert-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            font-family: 'Gamja Flower', cursive;\r\n");
      out.write("            /* font-family: 'IBM Plex Sans KR', sans-serif; */\r\n");
      out.write("        }\r\n");
      out.write("        div{box-sizing: border-box; border: 0px solid red;}\r\n");
      out.write("        .header_outer{\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("            border-bottom: 2px solid lightgray ;\r\n");
      out.write("            /* position: fixed; */\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .header_outer>div{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_loginSession{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 12%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_navi{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_left_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 2%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_right_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 1%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a { \r\n");
      out.write("        color: #000;\r\n");
      out.write("        display:inline-block; \r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        height: 1px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:after {\r\n");
      out.write("        display:block;\r\n");
      out.write("        content: '';\r\n");
      out.write("        border-bottom: solid 3px rgb(223, 188, 223);  \r\n");
      out.write("        transform: scaleX(0);  \r\n");
      out.write("        transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:hover:after {transform:scaleX(1);}\r\n");
      out.write("        .navi_detail td{\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: 75px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail div{\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img:hover{\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .moveTopBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 1rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 3.7rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn>svg, .moveTopBtn>svg{\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        color: rgb(253, 111, 182)\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"moveTopBtn\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-up-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"loginBtn\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
      out.write("            <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const $topBtn = document.querySelector(\".moveTopBtn\");\r\n");
      out.write("\r\n");
      out.write("        // 버튼 클릭 시 맨 위로 이동\r\n");
      out.write("        $topBtn.onclick = () => {\r\n");
      out.write("            window.scrollTo({ top: 0, behavior: \"smooth\" });  \r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
if (alertMsg != null){  
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        swal(\"");
      out.print(alertMsg);
      out.write("\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
session.removeAttribute("alertMsg"); // invalidate 쓰면 session 이 다 날아간다 따라서 이 세션만 지울수 있게 removeattribute 를 쓴다
      out.write("\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"header_outer\" align=\"center\">\r\n");
      out.write("        <div class=\"header_left_empty\"></div>\r\n");
      out.write("        <div class=\"header_logo\">\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("\"><img src=\"");
      out.print(contextPath);
      out.write("/resource/img/mainLogo/1번로고.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_loginSession\">\r\n");
      out.write("                <!-- 로그인 및 버튼 -->\r\n");
      out.write("    <div class=\"login_btn\">\r\n");
      out.write("        ");
if (loginMember == null ){ 
      out.write("\r\n");
      out.write("            <!-- The Modal -->\r\n");
      out.write("            <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal Header -->\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal body -->\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form action=\"");
      out.print(contextPath);
      out.write("/login.me\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" name = \"memId\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"pwd\">Password:</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" placeholder=\"Enter password\" name=\"memPwd\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" onclick=\"enroll();\">회원가입하기</button>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal footer -->\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                ");
}else{
      out.write("\r\n");
      out.write("                    <div style=\"line-height: 35px; text-align: center;\">\r\n");
      out.write("                    <p style=\"margin: 0; margin-top: 10px;\">\r\n");
      out.write("                    ");
if(loginMember.getTitleImg().length() > 5) { 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.print(loginMember.getTitleImg());
      out.write("\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.write("/resource/img/profile/기본이미지.png\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <strong>");
      out.print(loginMember.getNickname());
      out.write("님</strong> 반갑습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-sm btn-secondary\" href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">나의정보</a>\r\n");
      out.write("                    <button  class=\"btn btn-sm btn-danger\" onclick=\"location.href = '");
      out.print(contextPath);
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_navi\">\r\n");
      out.write("            <table class=\"navi_detail\" border=\"0\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/search.pl\"><div>해봄검색</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/searchCourse.pl\"><div>해봄코스</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1\"><div>자유게시판</div></a></td>\r\n");
      out.write("                    <td><a href=\"#\"><div>해봄의소리</div></a></td>\r\n");
      out.write("                    ");
if (loginMember != null && loginMember.getMemId().equals("admin")){ 
      out.write("\r\n");
      out.write("                        <!-- 관리자로 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myAdmin.ad\"><div>관리자페이지</div></a></td>\r\n");
      out.write("                    ");
} else {
      out.write("\r\n");
      out.write("                        ");
  if(loginMember != null) { 
      out.write("\r\n");
      out.write("                        <!-- 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\"><div>마이페이지</div></a></td>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_right_empty\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            function enroll(){\r\n");
      out.write("                location.href =  \"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
 System.out.println(loginMember); 
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\" style=\"padding: 20px 10px ;\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Indicators -->\r\n");
      out.write("            <ul class=\"carousel-indicators\">\r\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("                <li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("            <!-- The slideshow -->\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img src=\"resource/img/1mj3112000b8kyfpd5FC3_Z_640_10000_R5.png_.webp\" alt=\"Los Angeles\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <h3>워터밤</h3>\r\n");
      out.write("                        <p>놀러와~~~~~</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"resource/img/285632_356327_475.jpg\" alt=\"Chicago\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <h3>화로축제</h3>\r\n");
      out.write("                        <p>흠냐링~</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img src=\"resource/img/5n90r48nlara9vx.png\" alt=\"New York\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <h3>뮤직축제</h3>\r\n");
      out.write("                        <p></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Left and right controls -->\r\n");
      out.write("            <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div id=\"write-text\" style=\"padding: 10px;\">\r\n");
      out.write("            <div>\r\n");
      out.write("                글쓰기\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"insert.bo\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <input type=\"hidden\" name=\"userNo\" value=\"");
      out.print( loginMember.getMemNo());
      out.write("\">\r\n");
      out.write("            <div class=\"write-post-area\" style=\"padding: 10px;\">\r\n");
      out.write("                <div id=\"write-post-header\">\r\n");
      out.write("                    <div id=\"write-post-title-area\">\r\n");
      out.write("                        <input type=\"text\" id=\"write-post-title\" name=\"title\" placeholder=\"제목을 입력하세요.\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"select-category-area\">\r\n");
      out.write("                        <select name=\"category\" id=\"select-category\" onchange=\"clickNoticeOption(this.value);\">\r\n");
      out.write("                            <option value=\"F\">자유게시판</option>\r\n");
      out.write("                            ");
 if(loginMember.getGrade().equals("무궁화")){ 
      out.write("\r\n");
      out.write("                                <option value=\"N\">공지사항</option>\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                <option value=\"Q&A\">Q & A</option>\r\n");
      out.write("                                <option value=\"...\">...</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <textarea name=\"content\" id=\"write-post\" style=\"width: 100%; height: 500px; resize: none;\" required></textarea>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                <div id=\"input-tag\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <span class=\"parent-span\">\r\n");
      out.write("                        <span>#</span>\r\n");
      out.write("                        <div class=\"tag-input-area\">\r\n");
      out.write("                            <input class=\"tag-input\" type=\"text\" maxlength=\"50\" placeholder=\"태그입력\">\r\n");
      out.write("                            <button type=\"button\" class='delete-tag'>x</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <table align=\"center\" id=\"fileTable\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td width=\"20%\" height=\"120\" style=\"border: 1px solid gray;\"><img src=\"\" id=\"contentImg1\" width=\"100%\" height=\"100%\" onclick=\"chooseFile(1)\"></td>\r\n");
      out.write("                            <td width=\"20%\" height=\"120\" style=\"border: 1px solid gray;\"><img src=\"\" id=\"contentImg2\" width=\"100%\" height=\"100%\" onclick=\"chooseFile(2)\"></td>\r\n");
      out.write("                            <td width=\"20%\" height=\"120\" style=\"border: 1px solid gray;\"><img src=\"\" id=\"contentImg3\" width=\"100%\" height=\"100%\" onclick=\"chooseFile(3)\"></td>\r\n");
      out.write("                            <td width=\"20%\" height=\"120\" style=\"border: 1px solid gray;\"><img src=\"\" id=\"contentImg4\" width=\"100%\" height=\"100%\" onclick=\"chooseFile(4)\"></td>\r\n");
      out.write("                            <td width=\"20%\" height=\"120\" style=\"border: 1px solid gray;\"><img src=\"\" id=\"contentImg5\" width=\"100%\" height=\"100%\" onclick=\"chooseFile(5)\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div id=\"file-area\" style=\"display:none;\">\r\n");
      out.write("                        <input type=\"file\" name=\"file1\" id=\"file1\" onchange=\"loadImg(this, 1);\">\r\n");
      out.write("                        <input type=\"file\" name=\"file2\" id=\"file2\" onchange=\"loadImg(this, 2);\">\r\n");
      out.write("                        <input type=\"file\" name=\"file3\" id=\"file3\" onchange=\"loadImg(this, 3);\">\r\n");
      out.write("                        <input type=\"file\" name=\"file4\" id=\"file4\" onchange=\"loadImg(this, 4);\">\r\n");
      out.write("                        <input type=\"file\" name=\"file5\" id=\"file5\" onchange=\"loadImg(this, 5);\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"write-poster-footer\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <div id=\"writer-poster-submit\">\r\n");
      out.write("                        <input type=\"button\" value=\"등록\" onclick=\"postSubmit();\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"admin-private\" style=\"display: none;\">\r\n");
      out.write("                        <input type=\"checkbox\" id=\"notice-check\" name=\"noticeUp\" value=\"Y\">\r\n");
      out.write("                        <label for=\"notice-check\" id=\"notice-check-text\" style=\"font-size: 11px;\">상단고정</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" id=\"hiddenTag\" name=\"tag\">\r\n");
      out.write("        </form>\r\n");
      out.write("        <script>\r\n");
      out.write("            /* 해시태그 스크립트 */\r\n");
      out.write("            $(function () { \r\n");
      out.write("                \r\n");
      out.write("                $(document).on('keydown', '.tag-input', function () {\r\n");
      out.write("                    $(this).css('width', 20);\r\n");
      out.write("                    let value = $(this).val();\r\n");
      out.write("                    $('.tag-input-area').append('<div class=\"virtual\">' + value + '</div>')\r\n");
      out.write("                    \r\n");
      out.write("                    let inputWidth = $(this).siblings('.virtual').width()\r\n");
      out.write("                    $(this).css('width', inputWidth + 20);\r\n");
      out.write("                    $('.virtual').remove();\r\n");
      out.write("                    \r\n");
      out.write("                })\r\n");
      out.write("                $(document).on('click', '.delete-tag', function () {\r\n");
      out.write("                    let tagLength = $('.tag-input').length;\r\n");
      out.write("                    let ti = $('.tag-input').get()  \r\n");
      out.write("                    console.log($(this).prev().val())\r\n");
      out.write("                    console.log(ti[tagLength-1].value)\r\n");
      out.write("                    console.log($(\"button\").index(this))\r\n");
      out.write("                    console.log(tagLength-1)\r\n");
      out.write("                    if(($(\".delete-tag\").index(this)==tagLength-1) && (ti[tagLength-1]).value==''){    // 지금누른 버튼이 마지막 인덱스의 버튼일떄\r\n");
      out.write("                        $(this).prev().val('');\r\n");
      out.write("                    }else{\r\n");
      out.write("                        $(this).parent().parent().remove();\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("                $(document).on('change', '.tag-input', function () {\r\n");
      out.write("                        \r\n");
      out.write("                        let tagLength = $('.tag-input').length;\r\n");
      out.write("                        let ti = $('.tag-input').get()  \r\n");
      out.write("                        if(ti[tagLength-1].value != ''){\r\n");
      out.write("                            $(document).on('click', '.delete-tag', function () {\r\n");
      out.write("                                return;\r\n");
      out.write("                            })\r\n");
      out.write("    \r\n");
      out.write("                            $('#input-tag').append(\"<span class='parent-span'><span>#</span><div class='tag-input-area'><input class='tag-input' type='text' maxlength='50' placeholder='태그입력'><button type='button' class='delete-tag'>x</button></div></span>\");\r\n");
      out.write("                            $('.tag-input')[tagLength].focus();\r\n");
      out.write("                        }\r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            })\r\n");
      out.write("            // 등록하기 버튼 클릭시 폼 전송하는 함수\r\n");
      out.write("            function postSubmit(){\r\n");
      out.write("            	\r\n");
      out.write("            	let hashtag = $(\".parent-span input\");\r\n");
      out.write("            	let hashlist = [];\r\n");
      out.write("            	for(i = 0 ; i < hashtag.length-1; i++){\r\n");
      out.write("            		\r\n");
      out.write("            		console.log(hashtag[i].value)\r\n");
      out.write("					hashlist.push(hashtag[i].value)\r\n");
      out.write("					console.log(hashlist)\r\n");
      out.write("            	}\r\n");
      out.write("                $(\"#hiddenTag\").val(hashlist)\r\n");
      out.write("                console.log($(\"#hiddenTag\").val())\r\n");
      out.write("                let formSelect = $(\"form\").submit();\r\n");
      out.write("            }\r\n");
      out.write("            /*	$.ajax({\r\n");
      out.write("            		url:\"insert.bo\",\r\n");
      out.write("            		data:{boardTitle:$(\"#write-post-title\").val(),\r\n");
      out.write("            			  boardCategory:$(\"#select-category\").val(),\r\n");
      out.write("            			  boardContent:$(\"#write-post\").val(),\r\n");
      out.write("            			  hashList:$(\"#hiddenTag\").val(),\r\n");
      out.write("            			  type:\"post\",\r\n");
      out.write("            			  success:function(){\r\n");
      out.write("            				  console.log(\"성공\");\r\n");
      out.write("            			  },\r\n");
      out.write("            			  error:function(){\r\n");
      out.write("            				  console.log(\"실패\");\r\n");
      out.write("            			  }\r\n");
      out.write("            			  }\r\n");
      out.write("            	})\r\n");
      out.write("            }*/\r\n");
      out.write("    \r\n");
      out.write("            // select option에서 공지사항을 클릭했을때 상단게시체크박스가 나타나는 함수\r\n");
      out.write("            function clickNoticeOption(str){\r\n");
      out.write("				if(str=='N'){\r\n");
      out.write("					console.log(\"되나\")\r\n");
      out.write("					document.getElementById(\"admin-private\").style.display='';\r\n");
      out.write("                }else{\r\n");
      out.write("					document.getElementById(\"admin-private\").style.display='none';\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function chooseFile(i){\r\n");
      out.write("                $(\"#file\" + i).click(); \r\n");
      out.write("            }\r\n");
      out.write("            function loadImg(inputFile,i){\r\n");
      out.write("            	if(inputFile.files.length == 1){\r\n");
      out.write("            		const reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("                    reader.readAsDataURL(inputFile.files[0]);\r\n");
      out.write("\r\n");
      out.write("                    reader.onload = function(e){\r\n");
      out.write("                        switch(i){\r\n");
      out.write("                            case 1: $(\"#contentImg1\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                            case 2: $(\"#contentImg2\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                            case 3: $(\"#contentImg3\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                            case 4: $(\"#contentImg4\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                            case 5: $(\"#contentImg5\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }else{	\r\n");
      out.write("                    switch(i){\r\n");
      out.write("                    case 1: $(\"#contentImg1\").attr(\"src\", null); break;\r\n");
      out.write("                    case 2: $(\"#contentImg2\").attr(\"src\", null); break;\r\n");
      out.write("                    case 3: $(\"#contentImg3\").attr(\"src\", null); break;\r\n");
      out.write("                    case 4: $(\"#contentImg4\").attr(\"src\", null); break;\r\n");
      out.write("                    case 5: $(\"#contentImg5\").attr(\"src\", null); break;\r\n");
      out.write("                    \r\n");
      out.write("                    }\r\n");
      out.write("            	}\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
