/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-03 09:28:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.heabom.common.model.vo.PageInfo;
import com.heabom.board.model.vo.PrevNextPage;
import com.heabom.board.model.vo.Reply;
import java.lang.reflect.Field;
import com.heabom.common.model.vo.File;
import java.util.ArrayList;
import com.heabom.board.model.vo.Board;
import com.heabom.member.model.vo.Member;

public final class boardDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/board/../common/header.jsp", Long.valueOf(1693575024863L));
    _jspx_dependants.put("/views/board/../common/sidebar.jsp", Long.valueOf(1693492663994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.board.model.vo.PrevNextPage");
    _jspx_imports_classes.add("com.heabom.board.model.vo.Reply");
    _jspx_imports_classes.add("com.heabom.member.model.vo.Member");
    _jspx_imports_classes.add("com.heabom.common.model.vo.File");
    _jspx_imports_classes.add("com.heabom.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.heabom.board.model.vo.Board");
    _jspx_imports_classes.add("java.lang.reflect.Field");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Board b = (Board) request.getAttribute("b");
ArrayList<File> flist = (ArrayList<File>) request.getAttribute("flist");
ArrayList<Board> list = (ArrayList<Board>) request.getAttribute("list");
ArrayList<Reply> rlist = (ArrayList<Reply>) request.getAttribute("rlist");
PrevNextPage p = (PrevNextPage) request.getAttribute("p");

String boardNo = b.getBoardNo();
String boardTitle = b.getBoardTitle();
String writer = b.getWriter();
String boardContent = b.getBoardContent();
int boardCount = b.getBoardCount();
String createDate = b.getCreateDate();
String hashTag = b.getHashTagName();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("div {\r\n");
      out.write("	/*border: 1px solid red;*/\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap {\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	background-color: rgb(249, 238, 238);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrap>div {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin: 10px 20px 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-light {\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("/* 게시글 헤더 영역 */\r\n");
      out.write("#post_header {\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_header>div {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_category {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_category>a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_title {\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	line-height: 100px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	padding-right: 10px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_info {\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_info>div {\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_info img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_profile_img {\r\n");
      out.write("	width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_id {\r\n");
      out.write("	width: auto;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_grade {\r\n");
      out.write("	width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_grade img {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 6px;\r\n");
      out.write("	height: 50%;\r\n");
      out.write("	width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_header_footer {\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_header_footer>div {\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_date {\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	padding-right: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment>div {\r\n");
      out.write("	padding-left: 5px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	float: right;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment_img img {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment {\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("/* 게시글 헤더 영역 끝 */\r\n");
      out.write("\r\n");
      out.write("/* 게시글 content 영역 */\r\n");
      out.write("#post_content {\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_content>div {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_main {\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_main>* {\r\n");
      out.write("	padding: 50px 50px 100px 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_main img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_hashtag {\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	padding-right: 10px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_hashtag>a {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_content_footer {\r\n");
      out.write("	border-top: 1px solid gray;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_content_footer div {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_wish_img, #post_comment_img2, #post_report_img {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_content_footer img {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_content_footer span {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("}\r\n");
      out.write("/* 게시글 content 영역  끝 */\r\n");
      out.write("\r\n");
      out.write("/* 게시글 댓글 영역 */\r\n");
      out.write("#post_comment_area {\r\n");
      out.write("	height: auto;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	/*border: 1px solid purple;*/\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_area>div {\r\n");
      out.write("	padding-left: 20px;\r\n");
      out.write("	padding-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_header>div {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_header div {\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_filter_img {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_filter_img img {\r\n");
      out.write("	height: 40%;\r\n");
      out.write("	width: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_filter_text {\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	line-height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_filter_text>a {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_list {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	/*border: 1px solid blue; */\r\n");
      out.write("	border-top: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post_comment_list>div {\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	/*border: 1px solid green;*/\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	margin: 15px 0px 15px 0px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment>div {\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment_profile_img {\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	width: 4%;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment_profile_img img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment_box {\r\n");
      out.write("	width: 92%;\r\n");
      out.write("	height: auto; /* 바꿔야됨 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_comment_box>div>* {\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_user_info {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_userid {\r\n");
      out.write("	padding-top: 3px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_usergrade {\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_usergrade>img {\r\n");
      out.write("	padding-top: 40%;\r\n");
      out.write("	padding-right: 40%;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_text {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_info {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_date {\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	padding-right: 10px;\r\n");
      out.write("	color: rgb(58, 58, 58);\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_report {\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_report img {\r\n");
      out.write("	margin-bottom: 3px;\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	height: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_like {\r\n");
      out.write("	padding-top: 30px;\r\n");
      out.write("	width: 4%;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_like>div {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_like_img {\r\n");
      out.write("	height: 60%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_like_img img {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comment_like_count {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: 40%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_form {\r\n");
      out.write("	padding: 0 20px 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_box {\r\n");
      out.write("	border-radius: 10px 10px 10px 10px;\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	/*border: 1px solid green;*/\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	padding-right: 10px;\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_userid {\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding-top: 3px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_userid>a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_userid>span {\r\n");
      out.write("	padding-left: 85%;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_main {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment {\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	resize: none;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	overflow-wrap: break-word;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_footer {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#write_comment_footer>div {\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_upload_img {\r\n");
      out.write("	width: 95%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_upload_img>input {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_upload_img img {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	left: -33px;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_submit {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	width: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comment_submit>input {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("/* 게시글 댓글 영역 끝 */\r\n");
      out.write("\r\n");
      out.write("/* etc 영역 */\r\n");
      out.write("#post_etc {\r\n");
      out.write("	/*border: 1px solid red;*/\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("/* etc 영역 끝 */\r\n");
      out.write("\r\n");
      out.write("/* postlist 영역 */\r\n");
      out.write(".post_list { /* 인라인으로는 되는데 왜 css에서는 안되는지 모르겠네*/\r\n");
      out.write("	width: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_list>h3 {\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-area {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-area>tbody>tr:hover {\r\n");
      out.write("	background-color: lightgray;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new_post_title {\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	padding-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new_post_title>* {\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".new_post_title>div {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_writer {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_writer, .post_date {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_date {\r\n");
      out.write("	width: 10%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tfoot>tr {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_all_list {\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 60px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post_all_list:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/* postlist 영역 끝 */\r\n");
      out.write("\r\n");
      out.write("/* pagination 관련 */\r\n");
      out.write(".page-link {\r\n");
      out.write("	color: #000;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-item.active .page-link {\r\n");
      out.write("	/*z-index: 1;*/\r\n");
      out.write("	color: #555;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	border-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-link:focus, .page-link:hover {\r\n");
      out.write("	color: #000;\r\n");
      out.write("	background-color: #fafafa;\r\n");
      out.write("	border-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* pagination 관련 끝 */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath = request.getContextPath();
	Member loginMember =  (Member)session.getAttribute("loginMember");
	
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"wWidth=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=IBM+Plex+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script><!--alert-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            font-family: 'Gamja Flower', cursive;\r\n");
      out.write("            /* font-family: 'IBM Plex Sans KR', sans-serif; */\r\n");
      out.write("        }\r\n");
      out.write("        div{box-sizing: border-box; border: 0px solid red;}\r\n");
      out.write("        .header_outer{\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("            border-bottom: 2px solid lightgray ;\r\n");
      out.write("            /* position: fixed; */\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .header_outer>div{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_loginSession{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 12%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_navi{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_left_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 2%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_right_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 1%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a { \r\n");
      out.write("        color: #000;\r\n");
      out.write("        display:inline-block; \r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        height: 1px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:after {\r\n");
      out.write("        display:block;\r\n");
      out.write("        content: '';\r\n");
      out.write("        border-bottom: solid 3px rgb(223, 188, 223);  \r\n");
      out.write("        transform: scaleX(0);  \r\n");
      out.write("        transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:hover:after {transform:scaleX(1);}\r\n");
      out.write("        .navi_detail td{\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: 75px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail div{\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img:hover{\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .moveTopBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 1rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 3.7rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn>svg, .moveTopBtn>svg{\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        color: rgb(253, 111, 182)\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"moveTopBtn\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-up-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"loginBtn\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
      out.write("            <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const $topBtn = document.querySelector(\".moveTopBtn\");\r\n");
      out.write("\r\n");
      out.write("        // 버튼 클릭 시 맨 위로 이동\r\n");
      out.write("        $topBtn.onclick = () => {\r\n");
      out.write("            window.scrollTo({ top: 0, behavior: \"smooth\" });  \r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
if (alertMsg != null){  
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        swal(\"");
      out.print(alertMsg);
      out.write("\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
session.removeAttribute("alertMsg"); // invalidate 쓰면 session 이 다 날아간다 따라서 이 세션만 지울수 있게 removeattribute 를 쓴다
      out.write("\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"header_outer\" align=\"center\">\r\n");
      out.write("        <div class=\"header_left_empty\"></div>\r\n");
      out.write("        <div class=\"header_logo\">\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("\"><img src=\"");
      out.print(contextPath);
      out.write("/resource/img/mainLogo/1번로고.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_loginSession\">\r\n");
      out.write("                <!-- 로그인 및 버튼 -->\r\n");
      out.write("    <div class=\"login_btn\">\r\n");
      out.write("        ");
if (loginMember == null ){ 
      out.write("\r\n");
      out.write("            <!-- The Modal -->\r\n");
      out.write("            <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal Header -->\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal body -->\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form action=\"");
      out.print(contextPath);
      out.write("/login.me\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" name = \"memId\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"pwd\">Password:</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" placeholder=\"Enter password\" name=\"memPwd\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" onclick=\"enroll();\">회원가입하기</button>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal footer -->\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                ");
}else{
      out.write("\r\n");
      out.write("                    <div style=\"line-height: 35px; text-align: center;\">\r\n");
      out.write("                    <p style=\"margin: 0; margin-top: 10px;\">\r\n");
      out.write("                    ");
if(loginMember.getTitleImg().length() > 5) { 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.print(loginMember.getTitleImg());
      out.write("\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.write("/resource/img/profile/기본이미지.png\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <strong>");
      out.print(loginMember.getNickname());
      out.write("님</strong> 반갑습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-sm btn-secondary\" href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">나의정보</a>\r\n");
      out.write("                    <button  class=\"btn btn-sm btn-danger\" onclick=\"location.href = '");
      out.print(contextPath);
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_navi\">\r\n");
      out.write("            <table class=\"navi_detail\" border=\"0\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/search.pl\"><div>해봄검색</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/searchCourse.pl\"><div>해봄코스</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1\"><div>자유게시판</div></a></td>\r\n");
      out.write("                    <td><a href=\"#\"><div>해봄의소리</div></a></td>\r\n");
      out.write("                    ");
if (loginMember != null && loginMember.getMemId().equals("admin")){ 
      out.write("\r\n");
      out.write("                        <!-- 관리자로 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myAdmin.ad\"><div>관리자페이지</div></a></td>\r\n");
      out.write("                    ");
} else {
      out.write("\r\n");
      out.write("                        ");
  if(loginMember != null) { 
      out.write("\r\n");
      out.write("                        <!-- 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\"><div>마이페이지</div></a></td>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_right_empty\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            function enroll(){\r\n");
      out.write("                location.href =  \"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		<div id=\"post_header\">\r\n");
      out.write("			<div id=\"post_header\">\r\n");
      out.write("				<div id=\"notice_category\">\r\n");
      out.write("					");

					System.out.println(boardNo.substring(0, 1) + "ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ");
					
      out.write("\r\n");
      out.write("					");

					if (boardNo.substring(0, 1).equals("F")) {
					
      out.write("\r\n");
      out.write("					<a href=\"");
      out.print(contextPath);
      out.write("/list.bo?cpage=1\">자유게시판</a>\r\n");
      out.write("					");

					} else {
					
      out.write("\r\n");
      out.write("					<a href=\"#\">공지사항</a>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"post_title\">\r\n");
      out.write("					<span>");
      out.print(b.getBoardTitle());
      out.write("</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"user_info\">\r\n");
      out.write("					<div id=\"user_profile_img\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-login-310869.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"user_id\">\r\n");
      out.write("						<span>");
      out.print(b.getWriter());
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"user_grade\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-benefit-6000574.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"post_header_footer\">\r\n");
      out.write("					<div id=\"post_date\">\r\n");
      out.write("						<span>");
      out.print(b.getCreateDate());
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"post_comment\">\r\n");
      out.write("						<div class=\"post_comment_text\">\r\n");
      out.write("							<span>댓글 ");
      out.print(b.getCountReply());
      out.write("</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"post_comment_img\">\r\n");
      out.write("							<img src=\"resources/img/free-icon-add-comment-button-60782.png\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"post_content\">\r\n");
      out.write("			<div id=\"post_main\">\r\n");
      out.write("				<div>\r\n");
      out.write("					");
      out.print(b.getBoardContent());
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"post_hashtag\">\r\n");
      out.write("				");

				if (hashTag != null) {
				
      out.write("\r\n");
      out.write("				");

				String[] tagList = hashTag.split(",");
				
      out.write("\r\n");
      out.write("				");

				for (String s : tagList) {
				
      out.write("\r\n");
      out.write("				<a href=\"#\">#");
      out.print(s);
      out.write("</a>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"post_content_footer\">\r\n");
      out.write("				<div id=\"post_wish\">\r\n");
      out.write("					<div id=\"post_wish_img\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-star-5708819.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"width: auto;\">\r\n");
      out.write("						<span>찜하기</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"post_comment2\">\r\n");
      out.write("					<div id=\"post_comment_img2\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-add-comment-button-60782.png\"\r\n");
      out.write("							alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"post_comment_text2\" style=\"width: 720px;\">\r\n");
      out.write("						<span>댓글 ");
      out.print(b.getCountReply());
      out.write("</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"post_report\">\r\n");
      out.write("					<div id=\"post_report_img\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-siren-6043503.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<span>신고</span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"height: auto\">\r\n");
      out.write("			");

			if (flist.isEmpty()) {
			
      out.write("\r\n");
      out.write("			사진없다잉\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("			");

			System.out.println("됨?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ");
			
      out.write("\r\n");
      out.write("			");

			for (int i = 0; i < flist.size(); i++) {
			
      out.write("\r\n");
      out.write("			<img\r\n");
      out.write("				src=\"");
      out.print(contextPath);
      out.write('/');
      out.print(flist.get(i).getFilePath());
      out.write('/');
      out.print(flist.get(i).getChangeName());
      out.write("\"\r\n");
      out.write("				width=\"auto\" height=\"150\">\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"post_comment_area\">\r\n");
      out.write("			<div id=\"post_comment_header\">\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"width: 80px; line-height: 40px; font-weight: 600; font-size: 25px;\">\r\n");
      out.write("					<span>댓글</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<div id=\"comment_filter_img\">\r\n");
      out.write("						<img src=\"resources/img/filter-solid.svg\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"comment_filter_text\">\r\n");
      out.write("						<a href=\"#\">최신순</a> | <a href=\"#\">추천순</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"post_comment_list\">\r\n");
      out.write("				");

				System.out.println("진짜 이게 안됨?" + rlist);
				
      out.write("\r\n");
      out.write("				");

				if (rlist.isEmpty()) {
				
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"border: none; background-color: white; font-size: large; height: 100px;\">\r\n");
      out.write("					아직 등록된 댓글이 없습니다.</div>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				");

				for (Reply r : rlist) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"post_comment\">\r\n");
      out.write("					<div class=\"post_comment_profile_img\">\r\n");
      out.write("						<img src=\"resources/img/free-icon-login-310869.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"post_comment_box\">\r\n");
      out.write("						<div class=\"comment_user_info\">\r\n");
      out.write("							<div class=\"comment_userid\">\r\n");
      out.write("								");
      out.print(r.getReplyWriter());
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"comment_usergrade\">\r\n");
      out.write("								<img src=\"resources/img/free-icon-benefit-6000574.png\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"comment_text\">\r\n");
      out.write("							");
      out.print(r.getReplyContent());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"comment_info\">\r\n");
      out.write("							<div class=\"comment_date\">\r\n");
      out.write("								");
      out.print(r.getReplyDate());
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"comment_report\">\r\n");
      out.write("								<img src=\"resources/img/free-icon-siren-6043503.png\" alt=\"\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"comment_like\">\r\n");
      out.write("						<div class=\"comment_like_img\">\r\n");
      out.write("							<img src=\"resources/img/thumbs-up-regular.svg\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"comment_like_count\">\r\n");
      out.write("							");
      out.print(r.getReplyLike());
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<form action=\"insert.rp\" id=\"write_comment_form\" method=\"post\">\r\n");
      out.write("				<input type=\"hidden\" name=\"boardNo\" value=\"");
      out.print(boardNo);
      out.write("\">\r\n");
      out.write("				");

				if (loginMember != null) {
				
      out.write("\r\n");
      out.write("				<input type=\"hidden\" name=\"userNo\"\r\n");
      out.write("					value=\"");
      out.print(loginMember.getMemNo());
      out.write("\">\r\n");
      out.write("				<div id=\"write_comment_box\" style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"write_comment_userid\">\r\n");
      out.write("						<a href=\"#\">");
      out.print(loginMember.getMemId());
      out.write("</a> <span id=\"count_char\">0/500</span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"write_comment_main\">\r\n");
      out.write("						<!-- textarea는 이미지를 넣을수가 없음 어떻게 해결? 그리고 스크롤생김 -->\r\n");
      out.write("						<textarea name=\"reply-content\" id=\"write_comment\" cols=\"30\"\r\n");
      out.write("							rows=\"2\"></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"write_comment_footer\">\r\n");
      out.write("						<div id=\"comment_upload_img\">\r\n");
      out.write("							<input type=\"file\" name=\"rfile\" id=\"rfile\"> <img\r\n");
      out.write("								src=\"resources/img/free-icon-camera-685655.png\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"comment_submit\">\r\n");
      out.write("							<input class=\"btn btn-light btn-sm\" type=\"submit\" value=\"등록\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("			<script>\r\n");
      out.write("                $(function(){\r\n");
      out.write("                    function comment_ctrl(){\r\n");
      out.write("                        $(this).css('height', 'auto');\r\n");
      out.write("                        $(this).css('height',this.scrollHeight);\r\n");
      out.write("                        console.log(this.scrollHeight)\r\n");
      out.write("    \r\n");
      out.write("                        const count_char = $(this).val().length;\r\n");
      out.write("                        console.log(count_char)\r\n");
      out.write("                        $(\"#count_char\").text(count_char+\"/500\");\r\n");
      out.write("                        \r\n");
      out.write("                        if(count_char>=501){    // 근데 마우스로 붙여넣으면?\r\n");
      out.write("                            $(this).val($(this).val().substring(0,500));\r\n");
      out.write("                            alert(\"500자 이상 입력할 수 없습니다.\")\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    $(\"#write_comment\").keyup(comment_ctrl);\r\n");
      out.write("                    $(\"#write_comment\").keydown(comment_ctrl);\r\n");
      out.write("                    $(\"#write_comment\").click(function(){\r\n");
      out.write("                        $(this).css('outline','none')\r\n");
      out.write("                    })\r\n");
      out.write("                })\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div align=\"right\" id=\"delete-update-area\" style=\"width: auto;\">\r\n");
      out.write("			");
 if(loginMember != null && loginMember.getMemId().equals(b.getWriter())) { 
      out.write("\r\n");
      out.write("				<a class=\"btn btn-sm btn-warning\">수정하기</a>\r\n");
      out.write("				<a onclick=\"deleteConfirm();\" class=\"btn btn-sm btn-danger\">삭제하기</a>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("				<script>\r\n");
      out.write("					function deleteConfirm(){\r\n");
      out.write("						if(confirm(\"정말로 이 게시글을 삭제하시겠습니까?\")){\r\n");
      out.write("							location.href= href=\"");
      out.print( contextPath );
      out.write("/deleteForm.bo?bno=");
      out.print( b.getBoardNo() );
      out.write("\"\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				</script>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"post_etc\">\r\n");
      out.write("			<a type=\"button\" class=\"btn btn-light prev\"\r\n");
      out.write("				href=\"");
      out.print(contextPath);
      out.write("/detail.bo?bno=");
      out.print(p.getPrevPage());
      out.write("\">∧ 이전글</a>\r\n");
      out.write("			<a type=\"button\" class=\"btn btn-light next\"\r\n");
      out.write("				href=\"");
      out.print(contextPath);
      out.write("/detail.bo?bno=");
      out.print(p.getNextPage());
      out.write("\">∨ 다음글</a>\r\n");
      out.write("			<a type=\"button\" class=\"btn btn-light list\"\r\n");
      out.write("				href=\"");
      out.print(contextPath);
      out.write("/list.bo?cpage=1\">목록</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"post_list\" style=\"width: auto;\">\r\n");
      out.write("\r\n");
      out.write("						<input type=\"hidden\" id=\"cpage3\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("			<!-- 여기에 들어감 -->\r\n");
      out.write("\r\n");
      out.write("            <table id=\"dataTableBody\" style=\"width: 100%\">\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("			<ul class=\"page-item\"></ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	let listCount; // 현재 총 게시글 개수\r\n");
      out.write("	let currentPage = 1; //현재 페이지\r\n");
      out.write("	let pageLimit= 10; //  하단에 보여지는 페이징바의 최대개수	\r\n");
      out.write("	let boardLimit = 10; // 한 페이지내에 보여질 게시글 최대개수\r\n");
      out.write("	\r\n");
      out.write("	let maxPage ; // 가장마지막 페이지\r\n");
      out.write("	let startPage; // 페이징바의 시작수\r\n");
      out.write("	let endPage; // 페이징바의 끝 수\r\n");
      out.write("	\r\n");
      out.write("	let boardList; //표시하려하는 데이터 리스트\r\n");
      out.write("\r\n");
      out.write("		$(function(){\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("			 \r\n");
      out.write("			 $.ajax({ \r\n");
      out.write("				url: \"pageNation.bo\",\r\n");
      out.write("				success: function (plist) {\r\n");
      out.write("			        boardList= JSON.parse(plist);\r\n");
      out.write("				   	listCount = boardList.length;\r\n");
      out.write("			           console.log(listCount + \"!!!!\");\r\n");
      out.write("                       	maxPage = Math.ceil(listCount / boardLimit);\r\n");
      out.write("                       	startPage = (currentPage - 1) / pageLimit * pageLimit + 1;\r\n");
      out.write("                		endPage = startPage + pageLimit - 1;\r\n");
      out.write("\r\n");
      out.write("                        boardListView(1, boardLimit);\r\n");
      out.write("                		if(endPage > maxPage) {\r\n");
      out.write("                			endPage = maxPage;\r\n");
      out.write("                		};\r\n");
      out.write("                        \r\n");
      out.write("                        pagingBar(listCount, boardLimit, pageLimit, 1);\r\n");
      out.write("				}\r\n");
      out.write("			 });\r\n");
      out.write("			 \r\n");
      out.write("			})\r\n");
      out.write("			function boardListView(currentPage, boardLimit) {\r\n");
      out.write("			console.log(currentPage+ \"aaaa\" + boardLimit)\r\n");
      out.write("			  let chartHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("			currentPage = Number(currentPage);\r\n");
      out.write("			boardLimit = Number(boardLimit);\r\n");
      out.write("			let charTitleHtml = \r\n");
      out.write("			\"<tr><th style='width: 8%;'>글번호</th>\"+\r\n");
      out.write("	    	\"<th style='width: 57%;'>제목</th>\"+\r\n");
      out.write("	    	\"<th style='width: 10%;'>작성자</th>\"+\r\n");
      out.write("	    	\"<th style='width: 10%;'>조회수</th>\"+\r\n");
      out.write("	    	\"<th style='width: 15%;'>작성일</th></tr>\"\r\n");
      out.write("            ;\r\n");
      out.write("			// 총게시글 78개, 1페이지 인덱스 0 ~ 9 , 2페이지 인덱스 10 ~ 19, ..., 8페이지 인덱스 70 ~ 77\r\n");
      out.write("			if(currentPage == maxPage){\r\n");
      out.write("				  for (var i = (currentPage - 1) * boardLimit; i < (currentPage - 1) * boardLimit + (listCount % boardLimit) ;\r\n");
      out.write("				    i++\r\n");
      out.write("				  ) {\r\n");
      out.write("					  \r\n");
      out.write("		\r\n");
      out.write("					  console.log(boardList[i]);\r\n");
      out.write("					    chartHtml +=\r\n");
      out.write("					      \"<tr class='boardTr'><td>\" +\r\n");
      out.write("					      boardList[i].boardNo.substr(1) +\r\n");
      out.write("					      \"</td><td>\" +\r\n");
      out.write("					      boardList[i].boardTitle +\r\n");
      out.write("					      \"</td><td>\" +\r\n");
      out.write("					      boardList[i].writer +\r\n");
      out.write("					      \"</td><td>\" +\r\n");
      out.write("					      boardList[i].boardCount +\r\n");
      out.write("					      \"</td><td>\" +\r\n");
      out.write("					      boardList[i].createDate +\r\n");
      out.write("					      \"</td></tr>\";\r\n");
      out.write("				  }\r\n");
      out.write("			}else{\r\n");
      out.write("	\r\n");
      out.write("			  for (var i = (currentPage - 1) * boardLimit; i < (currentPage - 1) * boardLimit + boardLimit;\r\n");
      out.write("			    i++\r\n");
      out.write("			  ) {\r\n");
      out.write("				  \r\n");
      out.write("	\r\n");
      out.write("				  console.log(boardList[i]);\r\n");
      out.write("				    chartHtml +=           \r\n");
      out.write("\r\n");
      out.write("				      \"<tr class='boardTr'><td>\" +\r\n");
      out.write("				      boardList[i].boardNo.substr(1) +\r\n");
      out.write("				      \"</td><td>\" +\r\n");
      out.write("				      boardList[i].boardTitle +\r\n");
      out.write("				      \"</td><td>\" +\r\n");
      out.write("				      boardList[i].writer +\r\n");
      out.write("				      \"</td><td>\" +\r\n");
      out.write("				      boardList[i].boardCount +\r\n");
      out.write("				      \"</td><td>\" +\r\n");
      out.write("				      boardList[i].createDate +\r\n");
      out.write("				      \"</td></tr>\";\r\n");
      out.write("			  }\r\n");
      out.write("			  }\r\n");
      out.write("				  $(\"#dataTableBody\").html(charTitleHtml+chartHtml);\r\n");
      out.write("					\r\n");
      out.write("					$(\"#dataTableBody tr\").click(function () {\r\n");
      out.write("						console.log(\"크,ㄹ릭!!!\")\r\n");
      out.write("						console.log($(this).children().eq(0).text())\r\n");
      out.write("						location.href='");
      out.print( contextPath );
      out.write("/detail.bo?bno=' + $(this).children().eq(0).text()\r\n");
      out.write("\r\n");
      out.write("					})\r\n");
      out.write("	}\r\n");
      out.write("			 \r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("		function pagingBar(listCount, boardLimit, pageLimit, currentPage) {\r\n");
      out.write("			console.log(\"pageLimit\"+pageLimit)\r\n");
      out.write("			  console.log(\"currentPage : \" + currentPage);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			  let pageGroup = Math.ceil(currentPage / pageLimit); // 페이지 그룹\r\n");
      out.write("\r\n");
      out.write("			  let pageHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("			  if (currentPage > 1) {\r\n");
      out.write("			    pageHtml += \"<li><a href='#' id='prev'> 이전 </a></li>\";\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			 //페이징 번호 표시 \r\n");
      out.write("			  for (var i = startPage; i <= endPage; i++) {\r\n");
      out.write("				  console.log(endPage + \"ep\");\r\n");
      out.write("				  console.log(startPage + \"sp\");\r\n");
      out.write("			    if (currentPage == i) {\r\n");
      out.write("			      pageHtml +=\r\n");
      out.write("			        \"<li class='on' style='background-color: black'><a href='#' id='\" + i + \"'>\" + i + \"</a></li>\";\r\n");
      out.write("			    } else {\r\n");
      out.write("			      pageHtml += \"<li><a href='#' id='\" + i + \"'>\" + i + \"</a></li>\";\r\n");
      out.write("			    }\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  if (currentPage != maxPage) {\r\n");
      out.write("			    pageHtml += \"<li><a href='#' id='next'> 다음 </a></li>\";\r\n");
      out.write("			  }\r\n");
      out.write("\r\n");
      out.write("			  $(\".page-item\").html(pageHtml);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			  //페이징 번호 클릭 이벤트 \r\n");
      out.write("			  $(\".page-item li a\").click(function () {\r\n");
      out.write("			    let $id = $(this).attr(\"id\");\r\n");
      out.write("			    selectedPage = $(this).text();\r\n");
      out.write("\r\n");
      out.write("			    if ($id == \"next\") {\r\n");
      out.write("			    	selectedPage = currentPage + 1;\r\n");
      out.write("			    }\r\n");
      out.write("			    if ($id == \"prev\") {\r\n");
      out.write("			    	selectedPage = currentPage - 1;\r\n");
      out.write("			    }\r\n");
      out.write("			    \r\n");
      out.write("			    currentPage = selectedPage;\r\n");
      out.write("			    console.log(currentPage)\r\n");
      out.write("			    pagingBar(listCount, boardLimit, pageLimit, selectedPage);\r\n");
      out.write("			    boardListView(selectedPage, boardLimit);\r\n");
      out.write("			  });\r\n");
      out.write("			}\r\n");
      out.write("                    \r\n");
      out.write("			$(\"#boardLimit\").change(function () {\r\n");
      out.write("			    boardLimit = $(\"#boardLimit\").val();\r\n");
      out.write("			    pagingBar(listCount, boardLimit, pageLimit, currentPage);\r\n");
      out.write("			    boardListView(currentPage, boardLimit);\r\n");
      out.write("			 });\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
