/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-03 09:42:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.heabom.board.model.vo.Board;
import java.util.ArrayList;

public final class myBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Board> mblist = (ArrayList<Board>)request.getAttribute("blist");
	String bContextPath = request.getContextPath();

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    .yj_myBoard_area{\r\n");
      out.write("        border: 0px solid;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        width: 532px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        margin-left: 817px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .yj_myBoard_detail{\r\n");
      out.write("    height: auto;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    border: 1px solid lightgray;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .yj_myBoard_detail img{\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text_limit {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        text-overflow: ellipsis;  /* 말줄임 적용 */\r\n");
      out.write("        font-size: larger;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .detail_tb div, .detail_tb img{\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .text_limit a {\r\n");
      out.write("        color: blue;\r\n");
      out.write("        font-size: small;\r\n");
      out.write("        font-weight: bolder;\r\n");
      out.write("    }\r\n");
      out.write("    .text_limit a:hover {\r\n");
      out.write("        color: yellowgreen;\r\n");
      out.write("    }\r\n");
      out.write("    .text_limit:hover{\r\n");
      out.write("        color: darkgray;\r\n");
      out.write("    }\r\n");
      out.write("    #notMyboard{\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    #notMyBoard:hover{\r\n");
      out.write("        color: red;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"yj_myBoard_area\" align=\"cneter\">\r\n");
      out.write("    ");
 if(mblist.size() > 0) { 
      out.write("\r\n");
      out.write("    	");
 for(Board b : mblist) { 
      out.write("\r\n");
      out.write("        <div class=\"yj_myBoard_detail\">\r\n");
      out.write("            <table border=\"0\" class=\"detail_tb\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td rowspan=\"4\" width=\"300\" height=\"130\">\r\n");
      out.write("                    ");
 if( b.getBoardImg().length() > 5) {
      out.write("\r\n");
      out.write("                        <img src=\"");
      out.print(bContextPath );
      out.print(b.getBoardImg() );
      out.write("\" alt=\"\">\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    	<img src=\"https://breffee.net/data/editor/2210/20221013104826_fd5326c8ac17c04c88d91f03a8d313d8_5r8y.jpg\" alt=\"\">\r\n");
      out.write("                    ");
 } 
      out.write("    \r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td rowspan=\"4\" width=\"10\"></td>\r\n");
      out.write("                    <td height=\"40\" width=\"350\" colspan=\"4\"><div class=\"text_limit\"><strong>");
      out.print(b.getBoardTitle() );
      out.write("</strong></div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td height=\"30\" width=\"350\" colspan=\"4\"><div class=\"text_limit\">");
      out.print(b.getBoardContent() );
      out.write("</div></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                ");
 if(b.getHashTagName() == null ) { 
      out.write("\r\n");
      out.write("                	<td height=\"20\" width=\"350\" colspan=\"4\">\r\n");
      out.write("                		<div class=\"text_limit\" >\r\n");
      out.write("                			<a href=\"#\">#용산</a> <a href=\"#\">#불꽃축제</a> <a href=\"#\">#서울데이트</a> <a href=\"#\">#야경</a> <a href=\"#\">#우리동네뷰맛집</a>\r\n");
      out.write("               			</div>\r\n");
      out.write("            		</td>\r\n");
      out.write("           		");
 }else{ 
      out.write("\r\n");
      out.write("	                ");
 if((b.getHashTagName().length() - b.getHashTagName().replace(",", "").length()) > 0) { 
      out.write("\r\n");
      out.write("	                	");
 String[] hashlist = b.getHashTagName().split(",");
      out.write("\r\n");
      out.write("	                    <td height=\"20\" width=\"350\" colspan=\"4\">\r\n");
      out.write("	                    	<div class=\"text_limit\" >\r\n");
      out.write("	                    	");
 for(int i = 0 ; i<hashlist.length; i++) { 
      out.write("\r\n");
      out.write("	                    		<a href=\"#\">");
      out.print(hashlist[i] );
      out.write("</a></td>\r\n");
      out.write("	  	                	");
 } 
      out.write("\r\n");
      out.write("	  	                	</div>\r\n");
      out.write("	                ");
 }else{ 
      out.write("\r\n");
      out.write("	                	<td height=\"20\" width=\"350\" colspan=\"4\">\r\n");
      out.write("	                		<div class=\"text_limit\" >\r\n");
      out.write("	                			<a href=\"#\">");
      out.print(b.getHashTagName() );
      out.write("</a>\r\n");
      out.write("	               			</div>\r\n");
      out.write("	            		</td>\r\n");
      out.write("	                ");
 } 
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td width=\"120\" style=\"text-align: center; font-size: smaller;\">작성일: ");
      out.print(b.getCreateDate() );
      out.write("</td>\r\n");
      out.write("                    <td width=\"80\" style=\"text-align: center; font-size: smaller;\">조회수: ");
      out.print(b.getBoardCount() );
      out.write("</td>\r\n");
      out.write("                    <td width=\"150\" style=\"text-align: center; font-size: smaller;\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
 }else{ 
      out.write("\r\n");
      out.write("            <div class=\"yj_myBoard_detail\">\r\n");
      out.write("                <a id=\"notMyBoard\" href=\"");
      out.print(bContextPath);
      out.write("/list.bo?cpage=1\" style=\"color: black;\" >자유게시판에서 글을 작성해 보세요.</a>\r\n");
      out.write("            </div>\r\n");
      out.write("   	");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
