/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-31 19:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import java.sql.Date;
import com.heabom.member.model.vo.Member;

public final class myDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.member.model.vo.Member");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMember =  (Member)session.getAttribute("loginMember");
	String contextPath = request.getContextPath();

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 여기서부터 프로필 수정 */\r\n");
      out.write("        .prop_setting{\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            width: 533px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("            margin-left: 266px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .detail_title{\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            font-weight: bolder;\r\n");
      out.write("            font-size: small;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            background-color: rgb(216, 216, 216);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .prop_detail input {\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 230px;\r\n");
      out.write("            \r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        .prop_detail p {\r\n");
      out.write("            margin: -1px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #titleImg:hover{\r\n");
      out.write("        	cursor: pointer;\r\n");
      out.write("        	color:gray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String userNo = loginMember.getMemNo();
	String userId = loginMember.getMemId();
	String userPwd = loginMember.getMemPwd();
	String userName = loginMember.getMemName();
	String userPhone = loginMember.getMemPhone();
	String userNickname = loginMember.getNickname();
	String userEmail = (loginMember.getEmail() == null) ? "" : loginMember.getEmail();
	String userMbti = (loginMember.getMbit() == null) ? "" : loginMember.getMbit();
	String userBirth = (loginMember.getMemBirthday() == null) ? "1111-11-11" : loginMember.getMemBirthday();
	String[] userBirthList = userBirth.split("-");
	String userGrade = loginMember.getGrade();
	int userPoint = loginMember.getMemPoint();

      out.write("\r\n");
      out.write("<form action=\"");
      out.print(contextPath);
      out.write("/update.me\" id=\"enroll-form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <div class=\"prop_setting\">\r\n");
      out.write("        <input type=\"hidden\" name=\"userNo\" value=\"");
      out.print(userNo);
      out.write("\">\r\n");
      out.write("            <br>\r\n");
      out.write("    <table border=\"1\" class=\"prop_detail\" style=\"margin-bottom: 10px;\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\" width=\"100\">아이디<label for=\"\" style=\"color:hotpink\">&nbsp★&nbsp</label></td>\r\n");
      out.write("            <td width=\"245\">\r\n");
      out.write("                <input type=\"text\" readonly style=\"background-color: lightgray;\" name=\"userId\" value=\"");
      out.print(userId);
      out.write("\">\r\n");
      out.write("                <br><p style=\"font-size: smaller; color: red;\"><strong>&nbsp* 아이디는 수정 불가 사항입니다.</strong></p></td>\r\n");
      out.write("            <td rowspan=\"2\" width=\"120\">\r\n");
      out.write("                <img src=\"\" id=\"viewTitleImg\" name=\"viewTitleImg\" style=\"width: 120px; height: 120px;\">                        		\r\n");
      out.write("                <div id=\"file-area\" style=\"display: none;\">\r\n");
      out.write("                    <input type=\"file\" name=\"viewTitleImg\" id=\"enrolltitle\" onchange=\"loadImg(this);\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">비밀번호<label for=\"\" style=\"color:hotpink\">&nbsp★&nbsp</label></td>\r\n");
      out.write("            <td><input type=\"password\" name=\"userPwd\" id=\"updatePwd\" value=\"");
      out.print(userPwd);
      out.write("\" style=\"background-color: lightgray;\" required readonly><br><p style=\"font-size: smaller; color: green;\"><strong>&nbsp* 비밀번호 변경은 아래버튼을 눌러주세요</strong></p></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">이&nbsp&nbsp&nbsp름&nbsp</td>\r\n");
      out.write("            <td><input type=\"text\" placeholder=\"ex)홍길동\" readonly style=\"background-color: lightgray;\" name=\"userName\" value=\"");
      out.print(userName);
      out.write("\"></td>\r\n");
      out.write("            <td class=\"detail_title\" style=\"text-align: center;\"><p id=\"titleImg\" onclick=\"chooseFile();\">대표사진등록(변경)</p></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">이메일&nbsp</td>\r\n");
      out.write("            <td><input type=\"email\" placeholder=\"ex)해봄@SunSpring.com\" maxlength=\"30\" name=\"userEamil\" value=\"");
      out.print(userEmail);
      out.write("\"></td>\r\n");
      out.write("            <td class=\"\" rowspan=\"2\" style=\"text-align: center; font-size: smaller;\">\r\n");
      out.write("                <p style=\"color: blue;\"><strong>사진은 최대 10Mbyte를</strong></p>\r\n");
      out.write("                <p style=\"margin-bottom: 5px;\">넘을수 없습니다.</p>\r\n");
      out.write("                <p style=\"color: blue;\"><strong>사진 규격은 120*120를</strong></p>\r\n");
      out.write("                <p>권장합니다.</p>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">MBTI&nbsp</td>\r\n");
      out.write("            <td colspan=\"2\"><input type=\"text\" placeholder=\"ex)ESFJ(최대4글자)\" minlength=\"4\" maxlength=\"4\" name=\"userMbti\" value=\"");
      out.print(userMbti);
      out.write("\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\" colspan=\"\">휴대폰번호<label for=\"\" style=\"color:hotpink\">&nbsp★&nbsp</label></td>\r\n");
      out.write("            <td colspan=\"2\"><input type=\"text\" placeholder=\"ex)010-1234-5678\" minlength=\"13\" maxlength=\"13\" name=\"userPhone\" value=\"");
      out.print(userPhone);
      out.write("\" required><p style=\"font-size: smaller; color: green;\"><strong>&nbsp* 010-1234-5678과 같이 13자로 작성해주세요</strong></p></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\" colspan=\"\">닉네임<label for=\"\" style=\"color:hotpink\">&nbsp★&nbsp</label></td>\r\n");
      out.write("            <td colspan=\"2\"><input type=\"text\" placeholder=\"ex)동해번쩍서해번쩍\" name=\"nickName\" value=\"");
      out.print(userNickname);
      out.write("\" required></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">생년월일&nbsp</td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <select id=\"yearDropdown\" name=\"userYear\">\r\n");
      out.write("                    <option value=\"\" selected>");
      out.print(userBirthList[0] );
      out.write("</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <select id=\"monthDropdown\" name=\"userMonth\">\r\n");
      out.write("                    <option value=\"\" selected>");
      out.print(userBirthList[1] );
      out.write("</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <select id=\"dateDropdown\" name=\"userDay\">\r\n");
      out.write("                    <option value=\"\" selected>");
      out.print(userBirthList[2] );
      out.write("</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"hidden\" name=\"userBirth\" value=\"");
      out.print(userBirth);
      out.write("\">\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"detail_title\">등급 및 포인트&nbsp</td>\r\n");
      out.write("            <td colspan=\"2\">\r\n");
      out.write("                <input type=\"number\" style=\"width: 100px; background-color: lightgray;\" readonly value=\"");
      out.print(userPoint);
      out.write("\">\r\n");
      out.write("                <input type=\"text\" style=\"width: 100px; background-color: lightgray;\" readonly value=\"");
      out.print(userGrade);
      out.write("\">\r\n");
      out.write("                <p style=\"font-size: smaller; color: green;\"><strong>&nbsp* 획득한 포인트에 대한 등급입니다.</strong></p>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("                <input type=\"submit\" class=\"btn btn-sm btn-success style=\"background-color: pink; border: 1;\" value=\"정보변경\" onclick=\"return vaildatePwd();\">\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\" class=\"btn btn-sm btn-info\" data-toggle=\"modal\" data-target=\"#updatePwdModal\">비밀번호변경</a>\r\n");
      out.write("                <!--<button type=\"button\" class=\"btn btn-sm btn-warning\" data-toggle=\"modal\" data-target=\"#updatePwdModal\">비밀번호변경</button>-->\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\" class=\"btn btn-sm btn-warning\">취소</a>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-sm btn-danger\"data-toggle=\"modal\" data-target=\"#deleteModal\">회원탈퇴</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 비밀번호 변경용 Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"updatePwdModal\" align=\"center\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal body -->\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("                    <form action=\"");
      out.print( contextPath );
      out.write("/updatePwd.me\" method=\"post\">\r\n");
      out.write("                    	<input type=\"hidden\" name=\"userId\" value=\"");
      out.print( userId );
      out.write("\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>현재 비밀번호</td>\r\n");
      out.write("                                <td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>변경할 비밀번호</td>\r\n");
      out.write("                                <td><input type=\"password\" name=\"updatePwd\" required></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>변경할 비밀번호 확인</td>\r\n");
      out.write("                                <td><input type=\"password\" name=\"checkPwd\" required></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm btn-secondary\" onclick=\"return vaildatePwd()\">변경완료</button>\r\n");
      out.write("                        <br><br>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                function vaildatePwd(){\r\n");
      out.write("                    if($(\"input[name=updatePwd]\").val() != $(\"input[name=checkPwd]\").val()){\r\n");
      out.write("                        alert(\"변경할 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                </script>\r\n");
      out.write("                \r\n");
      out.write("    <!-- 회원탈퇴용 Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"deleteModal\" align=\"center\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Modal body -->\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("                    <form action=\"");
      out.print( contextPath );
      out.write("/updateStatus.me\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( userId );
      out.write("\">\r\n");
      out.write("                        <b>탈퇴 후 복구가 불가능 합니다. <br>\r\n");
      out.write("                        정말로 탈퇴 하시겠습니까? <br><br> </b>\r\n");
      out.write("\r\n");
      out.write("                        비밀번호 : <input type=\"password\" name=\"userPwd\" required> <br><br>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-sm btn-danger\" onclick=\"vaildateStatus()\">탈퇴하기</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	    populateYearDropdown();\r\n");
      out.write("	    populateMonthDropdown();\r\n");
      out.write("	    populateDateDropdown();\r\n");
      out.write("\r\n");
      out.write("	    document.getElementById('yearDropdown').addEventListener('change', populateDateDropdown);\r\n");
      out.write("	    document.getElementById('monthDropdown').addEventListener('change', populateDateDropdown);\r\n");
      out.write("}) \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("function populateYearDropdown() {\r\n");
      out.write("    let dropdown = document.getElementById('yearDropdown');\r\n");
      out.write("    for (let i = 1950; i <= 2020; i++) {\r\n");
      out.write("        let option = document.createElement('option');\r\n");
      out.write("        option.value = i;\r\n");
      out.write("        option.text = i + \"년\";\r\n");
      out.write("        dropdown.appendChild(option);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function populateMonthDropdown() {\r\n");
      out.write("    let dropdown = document.getElementById('monthDropdown');\r\n");
      out.write("    let months = [\r\n");
      out.write("        \"1월\", \"2월\", \"3월\", \"4월\", \"5월\", \"6월\",\r\n");
      out.write("        \"7월\", \"8월\", \"9월\", \"10월\", \"11월\", \"12월\"\r\n");
      out.write("    ];\r\n");
      out.write("    \r\n");
      out.write("    for (let i = 0; i < months.length; i++) {\r\n");
      out.write("        let option = document.createElement('option');\r\n");
      out.write("        option.value = i+1;\r\n");
      out.write("        option.text = months[i];\r\n");
      out.write("        dropdown.appendChild(option);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function populateDateDropdown() {\r\n");
      out.write("    let yearDropdown = document.getElementById('yearDropdown');\r\n");
      out.write("    let monthDropdown = document.getElementById('monthDropdown');\r\n");
      out.write("    let dateDropdown = document.getElementById('dateDropdown');\r\n");
      out.write("    \r\n");
      out.write("    while (dateDropdown.firstChild) {\r\n");
      out.write("        dateDropdown.removeChild(dateDropdown.firstChild);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let month = monthDropdown.value;\r\n");
      out.write("    let year = yearDropdown.value;\r\n");
      out.write("\r\n");
      out.write("    let daysInMonth;\r\n");
      out.write("    switch (month) {\r\n");
      out.write("        case '2':\r\n");
      out.write("            daysInMonth = (year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0)) ? 29 : 28; // Leap year check\r\n");
      out.write("            break;\r\n");
      out.write("        case '4':\r\n");
      out.write("        case '6':\r\n");
      out.write("        case '9':\r\n");
      out.write("        case '11':\r\n");
      out.write("            daysInMonth = 30;\r\n");
      out.write("            break;\r\n");
      out.write("        default:\r\n");
      out.write("            daysInMonth = 31;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    for (let i = 1; i <= daysInMonth; i++) {\r\n");
      out.write("        let option = document.createElement('option');\r\n");
      out.write("        option.value = i;\r\n");
      out.write("        option.text = i + \"일\";\r\n");
      out.write("        dateDropdown.appendChild(option);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function chooseFile(){\r\n");
      out.write("    $(\"#enrolltitle\").click();\r\n");
      out.write("}\r\n");
      out.write("function loadImg(inputFile){\r\n");
      out.write("    console.log(inputFile);\r\n");
      out.write("    // infutFile : 현재 변화가 생긴 input type = \"file\" 요소객체\r\n");
      out.write("    // num : 몇번째 input 요소인지 확인 후 해당 그영역에 미리보기 하기 위해 전달받는 숫자\r\n");
      out.write("\r\n");
      out.write("    // 선택된 파일이 있으면 inputFile.files[0]에 선택된 파일이 담겨 있음\r\n");
      out.write("    //                          => inputFile.files.length 또한 1이 될 것이다.\r\n");
      out.write("    if(inputFile.files.length == 1){ // 파일이 선택된 경우 => 파일을 읽어들여서 미리보기를 해야한다.\r\n");
      out.write("        // 파일을 읽어들일 FileReader 객체 생성\r\n");
      out.write("        const reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        // 파일을 읽어들이는 메소드 호출\r\n");
      out.write("        reader.readAsDataURL(inputFile.files[0]);\r\n");
      out.write("        // 해당 파일을 읽어들이는 순간 해당 이 파일만의 고유한 url 부여\r\n");
      out.write("\r\n");
      out.write("        // 파일 읽어들이기가 완료 됬다고 하면 실행할 함수를 정의해두기\r\n");
      out.write("        reader.onload = function(e){\r\n");
      out.write("            // e.target.result => 읽어들인 파일의 고유한 url\r\n");
      out.write("            $(\"#viewTitleImg\").attr(\"src\", e.target.result);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    } else { // 선택된 파일이 취소된 경우 => 미리보기한 것도 사라지게 만들어 주어야 한다.\r\n");
      out.write("        $(\"#viewTitleImg\").attr(\"src\", null);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
