/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-03 13:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.heabom.member.model.vo.Member;

public final class bannerListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/admin/../common/sidebar.jsp", Long.valueOf(1693492663994L));
    _jspx_dependants.put("/views/admin/../common/header.jsp", Long.valueOf(1693575024863L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>게시판4</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        div, input {\r\n");
      out.write("            border: 1px solid red;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            /*box-sizing: border-box;\r\n");
      out.write("            border: 1px solid black;*/\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrap {\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            background-color: #FDEEEE;\r\n");
      out.write("\r\n");
      out.write("            padding-top: 1%;\r\n");
      out.write("            padding-bottom: 1%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .background {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            height: 1000px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 4%;\r\n");
      out.write("            margin-bottom: 4%;\r\n");
      out.write("            \r\n");
      out.write("            background-color: #F2F2F2;\r\n");
      out.write("            /*border: 1px solid black;*/\r\n");
      out.write("            border-radius: 30px 30px 30px 30px;\r\n");
      out.write("\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header {\r\n");
      out.write("            height: 15%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content {\r\n");
      out.write("            height: 75%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #footer {\r\n");
      out.write("            height: 10%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header>div, #content>div, #footer>div {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_1, #header_5 {\r\n");
      out.write("            width: 8%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_2 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_3 {\r\n");
      out.write("            width: 24%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_4 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content_1, #content_3 {\r\n");
      out.write("            width: 8%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content_2 {\r\n");
      out.write("            width: 84%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #footer_1, #footer_4 {\r\n");
      out.write("            width: 8%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #footer_2 {\r\n");
      out.write("            width: 14%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #footer_3 {\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*---------------------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        #header2 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #strong {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            top: 9%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*-------------------테이블---------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        #content_2>table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("\r\n");
      out.write("            margin-top: 2%;\r\n");
      out.write("\r\n");
      out.write("            border-color: lightgray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table>thead {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table>#tbody {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            padding-top: 3%;\r\n");
      out.write("            padding-bottom: 3%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #tbody>tr>td {\r\n");
      out.write("            padding-top: 4%;\r\n");
      out.write("            padding-bottom: 4%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*----------------------------전체---------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        #header_3 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("\r\n");
      out.write("            /*border: 1px solid purple;*/\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            height: 30%;\r\n");
      out.write("\r\n");
      out.write("            top: 120px;\r\n");
      out.write("            bottom: 0px;\r\n");
      out.write("            left: 0px;\r\n");
      out.write("            right: 5px;\r\n");
      out.write("\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown>div {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown button, .dropdown a {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*----------------------------검색---------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        #header_4 {\r\n");
      out.write("            position: relative;\r\n");
      out.write("\r\n");
      out.write("            /*border: 1px solid purple;*/\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_form {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            height: 30%;\r\n");
      out.write("\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_form {\r\n");
      out.write("\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 70px;\r\n");
      out.write("            bottom: 0px;\r\n");
      out.write("            left: 200;\r\n");
      out.write("            right: 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_form>div {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_text {\r\n");
      out.write("            width: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_btn {\r\n");
      out.write("            width: 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #search_form input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*--------------------------페이지바---------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        .pagination {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("\r\n");
      out.write("            margin-right: 15%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-link {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*-------------------------- 버튼 ---------------------------------*/\r\n");
      out.write("        \r\n");
      out.write("        #button1 {\r\n");
      out.write("            width: 90px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("\r\n");
      out.write("            border: none;\r\n");
      out.write("            background-color: #3498db;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #button2 {\r\n");
      out.write("            width: 90px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #button3 {\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("\r\n");
      out.write("            width: 60%;\r\n");
      out.write("            height: 50%;\r\n");
      out.write("\r\n");
      out.write("            font-weight: 900;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("            \r\n");
      out.write("        /*-----------------------------------------------------*/\r\n");
      out.write("\r\n");
      out.write("        .dropdown button, .dropdown a {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border: 3px solid lightgray;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath = request.getContextPath();
	Member loginMember =  (Member)session.getAttribute("loginMember");
	
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"wWidth=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=IBM+Plex+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script><!--alert-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            font-family: 'Gamja Flower', cursive;\r\n");
      out.write("            /* font-family: 'IBM Plex Sans KR', sans-serif; */\r\n");
      out.write("        }\r\n");
      out.write("        div{box-sizing: border-box; border: 0px solid red;}\r\n");
      out.write("        .header_outer{\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("            border-bottom: 2px solid lightgray ;\r\n");
      out.write("            /* position: fixed; */\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .header_outer>div{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_loginSession{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 12%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_navi{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_left_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 2%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_right_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 1%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a { \r\n");
      out.write("        color: #000;\r\n");
      out.write("        display:inline-block; \r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        height: 1px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:after {\r\n");
      out.write("        display:block;\r\n");
      out.write("        content: '';\r\n");
      out.write("        border-bottom: solid 3px rgb(223, 188, 223);  \r\n");
      out.write("        transform: scaleX(0);  \r\n");
      out.write("        transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:hover:after {transform:scaleX(1);}\r\n");
      out.write("        .navi_detail td{\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: 75px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail div{\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img:hover{\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .moveTopBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 1rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 3.7rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn>svg, .moveTopBtn>svg{\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        color: rgb(253, 111, 182)\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"moveTopBtn\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-up-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"loginBtn\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
      out.write("            <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const $topBtn = document.querySelector(\".moveTopBtn\");\r\n");
      out.write("\r\n");
      out.write("        // 버튼 클릭 시 맨 위로 이동\r\n");
      out.write("        $topBtn.onclick = () => {\r\n");
      out.write("            window.scrollTo({ top: 0, behavior: \"smooth\" });  \r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
if (alertMsg != null){  
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        swal(\"");
      out.print(alertMsg);
      out.write("\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
session.removeAttribute("alertMsg"); // invalidate 쓰면 session 이 다 날아간다 따라서 이 세션만 지울수 있게 removeattribute 를 쓴다
      out.write("\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"header_outer\" align=\"center\">\r\n");
      out.write("        <div class=\"header_left_empty\"></div>\r\n");
      out.write("        <div class=\"header_logo\">\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("\"><img src=\"");
      out.print(contextPath);
      out.write("/resource/img/mainLogo/1번로고.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_loginSession\">\r\n");
      out.write("                <!-- 로그인 및 버튼 -->\r\n");
      out.write("    <div class=\"login_btn\">\r\n");
      out.write("        ");
if (loginMember == null ){ 
      out.write("\r\n");
      out.write("            <!-- The Modal -->\r\n");
      out.write("            <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal Header -->\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal body -->\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form action=\"");
      out.print(contextPath);
      out.write("/login.me\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" name = \"memId\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"pwd\">Password:</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" placeholder=\"Enter password\" name=\"memPwd\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" onclick=\"enroll();\">회원가입하기</button>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal footer -->\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                ");
}else{
      out.write("\r\n");
      out.write("                    <div style=\"line-height: 35px; text-align: center;\">\r\n");
      out.write("                    <p style=\"margin: 0; margin-top: 10px;\">\r\n");
      out.write("                    ");
if(loginMember.getTitleImg().length() > 5) { 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.print(loginMember.getTitleImg());
      out.write("\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.write("/resource/img/profile/기본이미지.png\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <strong>");
      out.print(loginMember.getNickname());
      out.write("님</strong> 반갑습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-sm btn-secondary\" href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">나의정보</a>\r\n");
      out.write("                    <button  class=\"btn btn-sm btn-danger\" onclick=\"location.href = '");
      out.print(contextPath);
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_navi\">\r\n");
      out.write("            <table class=\"navi_detail\" border=\"0\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/search.pl\"><div>해봄검색</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/searchCourse.pl\"><div>해봄코스</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1\"><div>자유게시판</div></a></td>\r\n");
      out.write("                    <td><a href=\"#\"><div>해봄의소리</div></a></td>\r\n");
      out.write("                    ");
if (loginMember != null && loginMember.getMemId().equals("admin")){ 
      out.write("\r\n");
      out.write("                        <!-- 관리자로 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myAdmin.ad\"><div>관리자페이지</div></a></td>\r\n");
      out.write("                    ");
} else {
      out.write("\r\n");
      out.write("                        ");
  if(loginMember != null) { 
      out.write("\r\n");
      out.write("                        <!-- 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\"><div>마이페이지</div></a></td>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_right_empty\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            function enroll(){\r\n");
      out.write("                location.href =  \"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"background\">\r\n");
      out.write("            <div id=\"header\">\r\n");
      out.write("                <div id=\"header_1\"></div>\r\n");
      out.write("                <div id=\"header_2\"><strong id=\"strong\">로고 관리</strong></div>\r\n");
      out.write("                <div id=\"header_3\"></div>\r\n");
      out.write("                <div id=\"header_4\"></div>\r\n");
      out.write("                <div id=\"header_5\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <div id=\"content_1\"></div>\r\n");
      out.write("                <div id=\"content_2\">\r\n");
      out.write("                    <table border=\"1\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <th width=\"120\">분류</th>\r\n");
      out.write("                            <th width=\"150\">이미지</th>\r\n");
      out.write("                            <th width=\"120\">관리</th>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody id=\"tbody\">\r\n");
      out.write("                            <form action=\"\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>로고 이미지</td>\r\n");
      out.write("                                    <td><img id=\"img1\" width=\"150\" height=\"50\" onclick=\"chooseFile(1);\"></td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <button type=\"submit\" id=\"button1\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                 </tr>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"content_3\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"footer\">\r\n");
      out.write("                <div id=\"footer_1\"></div>\r\n");
      out.write("                <div id=\"footer_2\"></div>\r\n");
      out.write("                <div id=\"footer_3\">\r\n");
      out.write("                    <div id=\"file-area\" style=\"display: none;\">\r\n");
      out.write("                        <input type=\"file\" name=\"file1\" id=\"file1\" onchange=\"loadImg(this, 1);\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <script>\r\n");
      out.write("                        function chooseFile(num) {\r\n");
      out.write("                            $(\"#file\" + num).click();\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        function loadImg(inputFile, num) {\r\n");
      out.write("                            if(inputFile.files.length == 1) {\r\n");
      out.write("                                const reader = new FileReader();\r\n");
      out.write("                                reader.readAsDataURL(inputFile.files[0]);\r\n");
      out.write("\r\n");
      out.write("                                reader.onload = function(e) {\r\n");
      out.write("                                    switch(num) {\r\n");
      out.write("                                        case 1: $(\"#img1\").attr(\"src\", e.target.result); break;\r\n");
      out.write("                                    }\r\n");
      out.write("                                }\r\n");
      out.write("                            }else {\r\n");
      out.write("                                switch(num) {\r\n");
      out.write("                                        case 1: $(\"#img1\").attr(\"src\", null); break;\r\n");
      out.write("                                    }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    </script>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"footer_4\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
