/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-03 15:02:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.place;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.heabom.common.model.vo.File;
import java.util.ArrayList;
import com.heabom.place.model.vo.Place;
import com.heabom.member.model.vo.Member;
import com.heabom.place.model.vo.Place;
import com.heabom.member.model.vo.Member;

public final class placeDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/place/../place/placeDetailReview.jsp", Long.valueOf(1693753075159L));
    _jspx_dependants.put("/views/place/../common/header.jsp", Long.valueOf(1693575024863L));
    _jspx_dependants.put("/views/place/../common/sidebar.jsp", Long.valueOf(1693492663994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.heabom.member.model.vo.Member");
    _jspx_imports_classes.add("com.heabom.place.model.vo.Place");
    _jspx_imports_classes.add("com.heabom.common.model.vo.File");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

     	Place place = (Place)request.getAttribute("placeInfo");
    	System.out.println("여기는 placeDetailView : "+place.getPlaceNo());
    	ArrayList<File> fileList = (ArrayList<File>)request.getAttribute("fileList");
    	System.out.println(place.getPlaceNo());     	
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        .wrap {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        width: 1900px;\r\n");
      out.write("        margin: 50px auto;\r\n");
      out.write("        background-color: #ffffff;\r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    .place-img {\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .place-img img {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        margin-left: 60px;\r\n");
      out.write("    }\r\n");
      out.write("    .place-description {\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("    }\r\n");
      out.write("    table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("    th, td {\r\n");
      out.write("        border-bottom: 1px solid #e5e5e5;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("    th {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: #777;\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    td {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    td a {\r\n");
      out.write("        color: #007BFF;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    .review-section {\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .review {\r\n");
      out.write("            border-bottom: 1px solid #e5e5e5;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .review:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        .review-author {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-text {\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-img {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-date {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("        }\r\n");
      out.write("        .report {\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        color: #007BFF;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        margin-top: 5px;\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("            .review-form {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-form textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-form button {\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            background-color: #007BFF;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .review-form button:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("        .review-form {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width: 900px;\r\n");
      out.write("        }\r\n");
      out.write("        .review-form textarea {\r\n");
      out.write("            resize: none;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-item active{\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-item{\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 500px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
 
	String contextPath = request.getContextPath();
	Member loginMember =  (Member)session.getAttribute("loginMember");
	
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"wWidth=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Gamja+Flower&family=IBM+Plex+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script><!--alert-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            font-family: 'Gamja Flower', cursive;\r\n");
      out.write("            /* font-family: 'IBM Plex Sans KR', sans-serif; */\r\n");
      out.write("        }\r\n");
      out.write("        div{box-sizing: border-box; border: 0px solid red;}\r\n");
      out.write("        .header_outer{\r\n");
      out.write("            width: 1900px;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("            border-bottom: 2px solid lightgray ;\r\n");
      out.write("            /* position: fixed; */\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .header_outer>div{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_loginSession{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 12%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_navi{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_left_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 2%;\r\n");
      out.write("        }\r\n");
      out.write("        .header_right_empty{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 1%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a { \r\n");
      out.write("        color: #000;\r\n");
      out.write("        display:inline-block; \r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        height: 1px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:after {\r\n");
      out.write("        display:block;\r\n");
      out.write("        content: '';\r\n");
      out.write("        border-bottom: solid 3px rgb(223, 188, 223);  \r\n");
      out.write("        transform: scaleX(0);  \r\n");
      out.write("        transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navi_detail a:hover:after {transform:scaleX(1);}\r\n");
      out.write("        .navi_detail td{\r\n");
      out.write("            font-size: x-large;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: 75px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img{\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail div{\r\n");
      out.write("            width: auto;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .navi_detail a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("        .header_logo img:hover{\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .moveTopBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 1rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        bottom: 3.7rem;\r\n");
      out.write("        right: 1rem;\r\n");
      out.write("        width: 2.5rem;\r\n");
      out.write("        height: 2.5rem;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("    }\r\n");
      out.write("    .loginBtn>svg, .moveTopBtn>svg{\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        color: rgb(253, 111, 182)\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"moveTopBtn\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-arrow-up-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"loginBtn\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\"/>\r\n");
      out.write("            <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const $topBtn = document.querySelector(\".moveTopBtn\");\r\n");
      out.write("\r\n");
      out.write("        // 버튼 클릭 시 맨 위로 이동\r\n");
      out.write("        $topBtn.onclick = () => {\r\n");
      out.write("            window.scrollTo({ top: 0, behavior: \"smooth\" });  \r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    ");
if (alertMsg != null){  
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        swal(\"");
      out.print(alertMsg);
      out.write("\");\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
session.removeAttribute("alertMsg"); // invalidate 쓰면 session 이 다 날아간다 따라서 이 세션만 지울수 있게 removeattribute 를 쓴다
      out.write("\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    <div class=\"header_outer\" align=\"center\">\r\n");
      out.write("        <div class=\"header_left_empty\"></div>\r\n");
      out.write("        <div class=\"header_logo\">\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("\"><img src=\"");
      out.print(contextPath);
      out.write("/resource/img/mainLogo/1번로고.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_loginSession\">\r\n");
      out.write("                <!-- 로그인 및 버튼 -->\r\n");
      out.write("    <div class=\"login_btn\">\r\n");
      out.write("        ");
if (loginMember == null ){ 
      out.write("\r\n");
      out.write("            <!-- The Modal -->\r\n");
      out.write("            <div class=\"modal\" id=\"myModal\">\r\n");
      out.write("                <div class=\"modal-dialog\">\r\n");
      out.write("                    <div class=\"modal-content\">\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal Header -->\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title\">로그인</h4>\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal body -->\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <form action=\"");
      out.print(contextPath);
      out.write("/login.me\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"아이디\" name = \"memId\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"pwd\">Password:</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" placeholder=\"Enter password\" name=\"memPwd\" value=\"admin\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" onclick=\"enroll();\">회원가입하기</button>\r\n");
      out.write("                \r\n");
      out.write("                        <!-- Modal footer -->\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                ");
}else{
      out.write("\r\n");
      out.write("                    <div style=\"line-height: 35px; text-align: center;\">\r\n");
      out.write("                    <p style=\"margin: 0; margin-top: 10px;\">\r\n");
      out.write("                    ");
if(loginMember.getTitleImg().length() > 5) { 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.print(loginMember.getTitleImg());
      out.write("\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 }else{ 
      out.write("\r\n");
      out.write("                    	<img src=\"");
      out.print(contextPath);
      out.write("/resource/img/profile/기본이미지.png\" id=\"viewTitleImg1\" name=\"viewTitleImg1\" style=\"width: 25px; height: 25px; border-radius: 50px;\">\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <strong>");
      out.print(loginMember.getNickname());
      out.write("님</strong> 반갑습니다.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"btn btn-sm btn-secondary\" href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">나의정보</a>\r\n");
      out.write("                    <button  class=\"btn btn-sm btn-danger\" onclick=\"location.href = '");
      out.print(contextPath);
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_navi\">\r\n");
      out.write("            <table class=\"navi_detail\" border=\"0\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/search.pl\"><div>해봄검색</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/searchCourse.pl\"><div>해봄코스</div></a></td>\r\n");
      out.write("                    <td><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?cpage=1\"><div>자유게시판</div></a></td>\r\n");
      out.write("                    <td><a href=\"#\"><div>해봄의소리</div></a></td>\r\n");
      out.write("                    ");
if (loginMember != null && loginMember.getMemId().equals("admin")){ 
      out.write("\r\n");
      out.write("                        <!-- 관리자로 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myAdmin.ad\"><div>관리자페이지</div></a></td>\r\n");
      out.write("                    ");
} else {
      out.write("\r\n");
      out.write("                        ");
  if(loginMember != null) { 
      out.write("\r\n");
      out.write("                        <!-- 로그인하면 -->\r\n");
      out.write("                        <td><a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\"><div>마이페이지</div></a></td>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header_right_empty\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            function enroll(){\r\n");
      out.write("                location.href =  \"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <h1 align=\"center\">");
      out.print(place.getPlaceTitle());
      out.write("</h1>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"place-img\" style=\"border: 1px solid black;\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container mt-3\">\r\n");
      out.write("               \r\n");
      out.write("                <div id=\"myCarousel\" class=\"carousel slide\">\r\n");
      out.write("                \r\n");
      out.write("                  <!-- Indicators -->\r\n");
      out.write("                  <ul class=\"carousel-indicators\">\r\n");
      out.write("                    <li class=\"item1 active\"></li>\r\n");
      out.write("                    ");
 for (int i = 0 ; i <fileList.size() ; i ++ ) { 
      out.write("\r\n");
      out.write("                    <li class=\"item");
      out.print(i);
      out.write("\"></li>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("                  <!-- The slideshow -->\r\n");
      out.write("                  <div class=\"carousel-inner\">\r\n");
      out.write("                    <div class=\"carousel-item active\">\r\n");
      out.write("                      <img src=\"");
      out.print(place.getTitleImg());
      out.write("\"  width=\"100%\" height=\"100%\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
 for (int i = 0 ; i <fileList.size() ; i ++ ) { 
      out.write("\r\n");
      out.write("                    <div class=\"carousel-item\">\r\n");
      out.write("                      <img src=\"");
      out.print(fileList.get(i).getFilePath());
      out.write("\"  width=\"100%\" height=\"100%\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <!-- Left and right controls -->\r\n");
      out.write("                  <a class=\"carousel-control-prev\" href=\"#myCarousel\">\r\n");
      out.write("                    <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <a class=\"carousel-control-next\" href=\"#myCarousel\">\r\n");
      out.write("                    <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- <img src=\"");
      out.print(place.getTitleImg());
      out.write("\"> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"place-description\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>글번호</th>\r\n");
      out.write("                    <td id =\"plNo\">");
      out.print(place.getPlaceNo());
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>번호</th>\r\n");
      out.write("                    <td>");
      out.print(place.getPhone() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>주소</th>\r\n");
      out.write("                    <td>");
      out.print(place.getAddress() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>내용</th>\r\n");
      out.write("                    <td>");
      out.print(place.getPlaceContent() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>오픈시간</th>\r\n");
      out.write("                    <td>");
      out.print(place.getStartTime() );
      out.write("시</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>닫는시간</th>\r\n");
      out.write("                    <td>");
      out.print(place.getEndTime() );
      out.write("시</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>별점</th>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    ");
 for (int i = 0 ; i < place.getStarPoint(); i ++){ 
      out.write("\r\n");
      out.write("                    	⭐\r\n");
      out.write("                    	");
} 
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>홈페이지</th>\r\n");
      out.write("                    <td><a href=\"");
      out.print(place.getPlaceUrl());
      out.write("\">사이트 이동</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>예상소요시간</th>\r\n");
      out.write("                    <td>");
      out.print(place.getUseTime() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>예상소요비용</th>\r\n");
      out.write("                    <td>");
      out.print(place.getUsePrice() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>좋아요</th>\r\n");
      out.write("                    <td id = \"likeCount\">");
      out.print(place.getLikeCount());
      out.write(" \r\n");
      out.write("                    \r\n");
      out.write("                    ");
if(loginMember != null){ 
      out.write("\r\n");
      out.write("                    <button onclick=\"likeup();\">좋아요</button>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("      // Activate Carousel\r\n");
      out.write("      $(\"#myCarousel\").carousel();\r\n");
      out.write("        \r\n");
      out.write("      // Enable Carousel Indicators\r\n");
      out.write("      $(\".item1\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(0);\r\n");
      out.write("      });\r\n");
      out.write("      $(\".item2\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(1);\r\n");
      out.write("      });\r\n");
      out.write("      $(\".item3\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(2);\r\n");
      out.write("      });\r\n");
      out.write("      $(\".item4\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(2);\r\n");
      out.write("      });\r\n");
      out.write("        \r\n");
      out.write("      // Enable Carousel Controls\r\n");
      out.write("      $(\".carousel-control-prev\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(\"prev\");\r\n");
      out.write("      });\r\n");
      out.write("      $(\".carousel-control-next\").click(function(){\r\n");
      out.write("        $(\"#myCarousel\").carousel(\"next\");\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function likeup(){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("                    //요청을 보내기 \r\n");
      out.write("                    url : \"likeup.pl\",\r\n");
      out.write("                    data : {input : $(\"#plNo\").html()}, //데이터 넘길때에는 무조건 중괄호 열어라\r\n");
      out.write("                    //키 벨류 세트로 보내야한다 데이터는 긍까 객체 안에 객체네..\r\n");
      out.write("\r\n");
      out.write("                    type : \"get\", // 요청방식 지정\r\n");
      out.write("                    success : function(result){ //성공시 응답 데이터가 자동으로 매개변수로 넘어온다\r\n");
      out.write("                        if(result == 99999){\r\n");
      out.write("                        	swal(\"이미 좋아요를 눌렀네요\");\r\n");
      out.write("                        }else{\r\n");
      out.write("                        console.log(\"ajax통신 성공!\")\r\n");
      out.write("                        $(\"#likeCount\").text(result);\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    error : function(){\r\n");
      out.write("                        console.log(\"ajax통신 실패!\")\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                })\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath1 = request.getContextPath();
	Member loginMember1 =  (Member)session.getAttribute("loginMember");

      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"/>\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    div{border: 0px solid red;}\r\n");
      out.write("    .yj_place_area{\r\n");
      out.write("        width: 900px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .yj_place_review{\r\n");
      out.write("        width: 900px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    p{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .preview_detail{\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .reviewText{\r\n");
      out.write("\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .reviewText:hover{\r\n");
      out.write("        color: darkgray;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"yj_place_area\" align=\"center\">\r\n");
      out.write("    <form id=\"uploadForm\" action=\"");
      out.print(contextPath1);
      out.write("/review.pl\" id=\"enroll-form\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <input type=\"file\" id=\"file\" name=\"file\" style=\"display:none;\">\r\n");
      out.write("            <div class=\"place_text\" align=\"center\">\r\n");
      out.write("                <textarea name=\"content\" id=\"content\" cols=\"118\" rows=\"5\" style=\"resize: none;\" placeholder=\"해봄은 여러분의 소중한 리뷰를 기다리고 있습니다.\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"text_btn\" align=\"center\" style=\"float: left; width: 900px;\">\r\n");
      out.write("            ");
 if(loginMember1 != null) { 
      out.write("\r\n");
      out.write("                <div class=\"options\" align=\"center\" style=\"text-align: right;\">\r\n");
      out.write("                    <button type=\"button\" id=\"uploadBtn\">파일첨부</button>\r\n");
      out.write("                    &lt; 별점 &gt;\r\n");
      out.write("                    <input type=\"hidden\" name=\"star\" id=\"star\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"refNo\" id=\"refNo\" value=\"");
      out.print(place.getPlaceNo());
      out.write("\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"writer\" id=\"writer\" value=\"");
      out.print(loginMember1.getMemNo());
      out.write("\">\r\n");
      out.write("                    <select name=\"starpoint\" id=\"starpoint\">\r\n");
      out.write("                            <option value=\"5\" selected>5점</option>\r\n");
      out.write("                            <option value=\"4\">4점</option>\r\n");
      out.write("                            <option value=\"3\">3점</option>\r\n");
      out.write("                            <option value=\"2\">2점</option>\r\n");
      out.write("                            <option value=\"1\">1점</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <input type=\"hidden\" id=\"getstar\" onclick=\"getStar(event);\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-sm btn-info\" onclick=\"insertReview();\">리뷰등록</button>\r\n");
      out.write("                        <button class=\"btn btn-sm btn-danger\" id=\"allreset\" type=\"reset\">초기화</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"yj_place_review\" align=\"center\">\r\n");
      out.write("    <div class=\"preview\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){ \r\n");
      out.write("	selectReplyList();\r\n");
      out.write("	setInterval(selectReplyList, 100000);\r\n");
      out.write("    $(\"#uploadBtn\").click(function(){\r\n");
      out.write("        $(\"#file\").click();\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    $(document).on('click','.reviewText',function(){\r\n");
      out.write("    $(this).next().css(\"display\",\"\")\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function uploadFile(){\r\n");
      out.write("    var form = $(\"#uploadForm\")[0];\r\n");
      out.write("    var formData = new FormData(form);\r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url:\"review.pl\",\r\n");
      out.write("        type:\"post\",\r\n");
      out.write("        data : formData,\r\n");
      out.write("        contentType : false,\r\n");
      out.write("        processData : false,\r\n");
      out.write("        success:function(){\r\n");
      out.write("            console.log(\"리뷰 사진 통신 성공!!!\")\r\n");
      out.write("        },\r\n");
      out.write("        error:function(){\r\n");
      out.write("            console.log(\"리뷰 사진 통신 실패ㅠㅠ\")\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getStar(event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("    let star = $(\"#starpoint option:selected\").val();\r\n");
      out.write("    $(\"#star\").val(star);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectReplyList(){\r\n");
      out.write("    $.ajax({\r\n");
      out.write("    	url:\"rlist.pl\",\r\n");
      out.write("    	type:\"post\",\r\n");
      out.write("    	data:{\r\n");
      out.write("    		pNo:$(\"#refNo\").val()\r\n");
      out.write("    	},\r\n");
      out.write("        success:function(list){\r\n");
      out.write("        	console.log(list);\r\n");
      out.write("            console.log(\"ajax 리뷰조회 성공 !!!\")\r\n");
      out.write("            let result = \"\";\r\n");
      out.write("            $(\".preview\").html(\"\");\r\n");
      out.write("            for(let i=0; i<list.length; i++){\r\n");
      out.write("                result += `<table class=\"preview_detail\" border=\"2\">\r\n");
      out.write("			                <tr>\r\n");
      out.write("			                    <td rowspan=\"2\" width=\"80\" height=\"80\">\r\n");
      out.write("			                    	<div align=\"center\">`\r\n");
      out.write("			                    	if(list[i].userImgPath && list[i].userImgPath.length < 5) {\r\n");
      out.write("			    						result +=	`<img src=\"");
      out.print(contextPath1);
      out.write("/resource/img/profile/기본이미지.png\" name=\"viewTitleImg\" style=\"width: 75px; height: 75px; border-radius: 20px;\">`\r\n");
      out.write("			                            } else {\r\n");
      out.write("			                            result += 	`<img src=\"");
      out.print(contextPath1);
      out.write("/${list[i].userImgPath}\" name=\"viewTitleImg\" style=\"width: 75px; height: 75px; border-radius: 20px;\">`\r\n");
      out.write("			    						}\r\n");
      out.write("			    						result += `</div>\r\n");
      out.write("			                    </td>\r\n");
      out.write("			                    <td colspan=\"2\">\r\n");
      out.write("			                    별점(`\r\n");
      out.write("			                    	for(let j = 0; j<list[i].reRefStar; j++) { \r\n");
      out.write("			                    	result += `⭐`\r\n");
      out.write("			                    	}\r\n");
      out.write("			                    	result += `)${list[i].reRefStar}\r\n");
      out.write("			                    </td>\r\n");
      out.write("			                </tr>\r\n");
      out.write("			                <tr>\r\n");
      out.write("			                    <td colspan=\"2\">${list[i].nickname} | ${list[i].reDate} | <a href=\"\">신고</a></td>\r\n");
      out.write("			                </tr>`\r\n");
      out.write("			                if( list[i].imgPath != \"/\") {\r\n");
      out.write("			                result +=  `<tr>\r\n");
      out.write("			                    <td colspan=\"2\" width=\"550\">\r\n");
      out.write("			                        <p class=\"reviewText\"> ${list[i].reContent}</p>\r\n");
      out.write("			                        <div class=\"noneImg\" align=\"center\" style=\"display:none\">\r\n");
      out.write("			                            <img src=\"");
      out.print(contextPath1);
      out.write("/${list[i].imgPath}\" alt=\"\" width=\"350\" height=\"300\">  \r\n");
      out.write("			                        </div>\r\n");
      out.write("			                    </td>\r\n");
      out.write("			                    <td width=\"130\" height=\"130\">\r\n");
      out.write("			                        <img src=\"");
      out.print(contextPath1);
      out.write("/${list[i].imgPath}\" alt=\"\" width=\"130\" height=\"130\">  \r\n");
      out.write("			                    </td>\r\n");
      out.write("			                </tr>\r\n");
      out.write("			            </table>`\r\n");
      out.write("			            \r\n");
      out.write("			            } else {\r\n");
      out.write("			            result += `<tr>\r\n");
      out.write("			                    <td colspan=\"2\" width=\"680\" height=\"50\">\r\n");
      out.write("			                    <p style=\"padding: 10px;\"> ${list[i].reContent} </p>\r\n");
      out.write("			                    </td>\r\n");
      out.write("			                </tr>\r\n");
      out.write("			            </table>`\r\n");
      out.write("			            }\r\n");
      out.write("            }\r\n");
      out.write("            $(\".preview\").html(result);\r\n");
      out.write("        },\r\n");
      out.write("        error:function(){\r\n");
      out.write("            console.log(\"ajax 리뷰죠회 실패 ㅠㅠ\")\r\n");
      out.write("        }\r\n");
      out.write("    })\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 등록 및 동기화\r\n");
      out.write("async function insertReview() {\r\n");
      out.write("	insertReview1();\r\n");
      out.write("    const result = await selectReplyList1();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("function selectReplyList1(){\r\n");
      out.write("    return new Promise((resolve) => {\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            selectReplyList();\r\n");
      out.write("        }, 100);\r\n");
      out.write("    })\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function insertReview1(){\r\n");
      out.write("    $(\"#getstar\").click();\r\n");
      out.write("    uploadFile();\r\n");
      out.write("\r\n");
      out.write("    var form = $(\"#uploadForm\")[0];\r\n");
      out.write("    var formData = new FormData(form);\r\n");
      out.write("    \r\n");
      out.write("    console.log(form)\r\n");
      out.write("    console.log(formData)\r\n");
      out.write("      \r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"review.pl\",\r\n");
      out.write("		data:{\r\n");
      out.write("			content:$(\"#content\").val(),\r\n");
      out.write("			star:$(\"#star\").val(),\r\n");
      out.write("			refNo:$(\"#refNo\").val(),\r\n");
      out.write("			writer:$(\"#writer\").val(),\r\n");
      out.write("            file:formData,\r\n");
      out.write("		},\r\n");
      out.write("		contentType:false,\r\n");
      out.write("        processData:false,\r\n");
      out.write("		type:\"post\",\r\n");
      out.write("		success:function(result){\r\n");
      out.write("				// 한번더 불러줘서 갱신된 글을 불러 준다.\r\n");
      out.write("			console.log(result);\r\n");
      out.write("            console.log(\"리뷰작성 ajax 통신 성공!!!\");\r\n");
      out.write("            $(\"#content\").val(\"\");\r\n");
      out.write("             \r\n");
      out.write("			if(result > 0){ // 댓글작성 성공! => 갱신된 댓글 리스트 조회\r\n");
      out.write("				$(\"#allreset\").click(); // 정상적으로 입력했으면, 초기화 해준다.\r\n");
      out.write("			}else{\r\n");
      out.write("				console.log(\"result 문제발생!!!!\");	\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		},\r\n");
      out.write("		error:function(){\r\n");
      out.write("			console.log(\"리뷰작성 ajax 통신 실패 ㅠㅠ\");\r\n");
      out.write("		}\r\n");
      out.write("			  \r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
